AWSTemplateFormatVersion: 2010-09-09
Description: Basci S3 Bucket CloudFormation template
Resources:
  S3bkforweb:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
Outputs:
  BucketName:
    Value: !Ref S3bkforweb
    Description: Name of s3 bucket